fs_mail:
  image: tianon/true
  volumes:
    #- ./spamassassin:/tmp/spamassassin/
    #- ./postfix:/tmp/postfix/
    #- ./letsencrypt/etc:/etc/letsencrypt
    - maildata:/var/mail
    - mailstate:/var/mail-state
    - ./config/:/tmp/docker-mailserver

mail:
  image: tvial/docker-mailserver:2.1
  hostname: mail
  domainname: dina-web.net
  environment:
    - DMS_SSL=selfsigned
  #environment:
  #  - ENABLE_SPAMASSASSIN=1
  #  - ENABLE_CLAMAV=1
  #  - ENABLE_FAIL2BAN=1
  #  - ENABLE_POSTGREY=1
  #  - ONE_DIR=1
  #  - DMS_DEBUG=0
  ports:
    - "25:25"
    - "143:143"
    - "587:587"
    - "993:993"
  volumes_from:
    - fs_mail
