version: '2'

services:

  fs_mail:
    image: tianon/true
    volumes:
      - ./maildata:/var/mail
      - ./mailstate:/var/mail-state
      - ./config:/tmp/docker-mailserver
      - ./certs:/tmp/ssl:ro

  mail:
    image: tvial/docker-mailserver:2.2
    hostname: mail
    domainname: dina-web.net
    container_name: mail
    environment:
      - DMS_SSL=selfsigned
      - ENABLE_SPAMASSASSIN=1
      - ENABLE_CLAMAV=1
    #  - ENABLE_FAIL2BAN=1
    #  - ENABLE_POSTGREY=1
    #  - ONE_DIR=1
      - DMS_DEBUG=0 # 1when testing, gives a good startup-log
      - SSL_TYPE=manual
      - SSL_CERT_PATH=/tmp/ssl/dina-web.net.crt
      - SSL_KEY_PATH=/tmp/ssl/dina-web.net.key # private key
    ports:
      - "25:25"
      - "143:143"
      - "587:587"
      - "993:993"
    volumes_from:
      - fs_mail
